name: moomapdrawer
author: abidibo
category: Interface
tags: [maps, drawer, googlemaps]
docs: http://www.abidibo.net/projects/js/moomapdrawer
demo: http://www.abidibo.net/projects/js/moomapdrawer/demo
current: 0.1.2
